# settings.py

# экран
SCREEN_WIDTH = 480
SCREEN_HEIGHT = 640
FPS = 60

# цвета
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BLUE = (135, 206, 250)
GREEN = (50, 205, 50)
RED = (255, 0, 0)

# натсройки игрока
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 60
PLAYER_START_X = SCREEN_WIDTH // 2
PLAYER_START_Y = SCREEN_HEIGHT - 100
PLAYER_SPEED = 5

# настройки платформы
PLATFORM_WIDTH = 70
PLATFORM_HEIGHT = 20
PLATFORM_SPEED = 2
PLATFORM_COLOR = GREEN

#
GRAVITY = 0.5
JUMP_STRENGTH = -10

LEVEL_SPEED_INCREASE = 0.5


ASSETS_DIR = "assets/"
IMAGES_DIR = ASSETS_DIR + "images/"
SOUNDS_DIR = ASSETS_DIR + "sounds/"
DATA_DIR = "data/"
