# settings.py

SCREEN_WIDTH = 480
SCREEN_HEIGHT = 640
FPS = 60
GRAVITY = 0.95

BLUE = (90, 206, 250)
TEXT_COLOR = (50, 50, 50)

# игрок
PLAYER_START_X = SCREEN_WIDTH // 2
PLAYER_START_Y = SCREEN_HEIGHT - 100
PLAYER_SPEED = 5
JUMP_STRENGTH = -15

# платформы
PLATFORM_WIDTH_MIN = 30
PLATFORM_WIDTH_MAX = 120
PLATFORM_HEIGHT = 20
PLATFORM_SPEED_MIN = 1
PLATFORM_SPEED_MAX = 3

BACKGROUND_IMAGE = "assets/images/background.jpg"
UI_FONT = None
